Portfolio: setup and mobile first (project)
odaialazzeh/Portfolio pull request #1
Opened 2022-09-21 16:54 UTC by odaialazzeh

- Check the linters.
- Update a README file.
- Add an index.html.
- Add a style.css.
- Open a pull request.

2022-09-21 17:36 UTC, frank1738 requested changes
Hi @odaialazzeh , 

Exellent job so far on your project! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good Design👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 17:36 UTC, frank1738 commented on index.html
> +            </nav>
- [ ] Kindly wrap your toolbar section in a `<header>` tag instead of a `<section>` . This is important for accessibility. Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

2022-09-21 17:36 UTC, frank1738 commented on index.html
> +                <h1>Welcome</h1>
- [ ] Kindly wrap your logo in an `<a>` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-09-21 17:36 UTC, frank1738 commented on index.html
> +                <img src="images/Icon - Menu.svg" alt="">
- [ ] Kindly wrap your hamburger button in a `<nav>` tag. The `nav` tag is for semantics reasons

2022-09-21 19:19 UTC, ichala approved these changes
Hi @odaialazzeh ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implement✔️

 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

*************************************
# Optional Suggestions 

- [ ] N/A


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 19:27 UTC, merged

2022-10-04 07:30 UTC, yash244466666 commented
@odaialazzeh great work, keep it up 😊😊😊😊😊😊😊😊

2022-10-04 07:36 UTC, Robison-faike123 commented
the code have many unsed code and if removed it will look wow