Portfolio: popup window
odaialazzeh/Portfolio pull request #10
Opened 2022-10-19 08:26 UTC by odaialazzeh

- [ ] Update the HTML file and add functions that are related to a popup window.
- [ ] Update the CSS file with styles to the popup class.
- [ ] Added images related to the popup class.
- [ ] Update the javascript file with the code to create a popup class and close and open the popup window.
- [ ] Update .eslintrc file.

2022-10-19 08:37 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @odaialazzeh, @girma336 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Github flow
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 08:37 UTC, HAMMAS-SALEEM commented on index.html
>                              <h3>Multi-Post Stories Gain+Glory</h3>
- [ ] Kindly comment these cards from your html file and generate your cards dynamically from javascript using an array of objects 😊 
- [ ] Your popup is showing the same data kindly implement your popup logic using the same array of objects which you will make for your cards 👍 

**Note:** You can see this [javascript file](https://github.com/HAMMAS-SALEEM/Portfolio/pull/16/files#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28f) to get an understanding how to implement both of these requirements 👍

2022-10-19 12:14 UTC, mckent05 requested changes
Hi @odaialazzeh,

# STATUS: CHANGES REQUIRED ♻️ ♻️ 
 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your portfolio looks nice 👍 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 12:14 UTC, mckent05 commented on function.js
> +};
- Just like the previous reviewer suggested, you are required to use an array of different objects to store different projects. You have used an object in your project please fix this 🙏 
- Also, like the previous reviewer suggested, all your projects= cards are displaying the same details (as a result of using just one object as I stated above). I'd suggest you ensure each card displays different details 😄 😄

2022-10-20 08:28 UTC, andersonlebon commented on index.html
>                  <img id="img10" src="images/Indicator.svg" alt="">
[OPTIONAL]. The design is great, but it can be better if you show images for each project :smile: 
![Screenshot from 2022-10-20 10-21-31](https://user-images.githubusercontent.com/65068771/196896662-bb461d6f-567f-4660-af59-3494ff494777.png)

2022-10-20 08:31 UTC, merged